//
// Created by josh on 11/9/22.
//

#pragma once
#ifndef VK_NO_PROTOTYPES
    #define VK_NO_PROTOTYPES
#endif
#define VULKAN_HPP_NO_SETTERS
#define VULKAN_HPP_NO_SMART_HANDLE
#define VULKAN_HPP_NO_SPACESHIP_OPERATOR
#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#define VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL 0
#define VULKAN_HPP_NO_TO_STRING
#include <vulkan/vulkan.hpp>
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 0
#ifdef VMA_STATIC_VULKAN_FUNCTIONS
    #undef VMA_STATIC_VULKAN_FUNCTIONS
#endif
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#include "vk_mem_alloc.h"